
# pyproject.toml

[tool.pytest.ini_options]
filterwarnings = [
    "ignore",
    "ignore::UserWarning",
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:function ham\(\) is deprecated:DeprecationWarning',
]
