name: docs

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.5
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: install
      run: | 
        echo "Compiling the code..."
        echo "using python:" `which python3` "and version:" `python3 --version` 
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: install_pandoc
      run: |
        conda install -c conda-forge pandoc
    - name:  docs
      run: |
        cd docs
        echo "cleaning docs...."
        echo "from" `pwd`
        make clean
        make html
  
